### ISSUE TITLE
cp: cannot stat '/wordlist.txt': No such file or directory

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [rojopolis/spellcheck-github-actions#1]
Spell check failed with the following error: 

```
Run rojopolis/spellcheck-github-actions@0.2.0
/usr/bin/docker run ...<concealed>...
cp: cannot stat '/wordlist.txt': No such file or directory
['aspell', '--lang', 'en', '--encoding', 'utf-8', 'create', 'master', '/github/workspace/wordlist.dic']
Current wordlist: 'wordlist.txt'
Problem compiling dictionary. Check the binary path and options.
Traceback (most recent call last):
  File "/usr/local/bin/pyspelling", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__main__.py", line 34, in main
    debug=args.debug
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__main__.py", line 59, in run
    debug=debug
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__init__.py", line 662, in spellcheck
    for result in spellchecker.run_task(task, source_patterns=sources):
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__init__.py", line 298, in run_task
    personal_dict = self.setup_dictionary(task)
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__init__.py", line 340, in setup_dictionary
    output
  File "/usr/local/lib/python3.7/site-packages/pyspelling/__init__.py", line 370, in compile_dictionary
    with open(wordlist, 'rb') as src:
FileNotFoundError: [Errno 2] No such file or directory: 'wordlist.txt'
##[error]Docker run failed with exit code 1
```

**Comment by facelessuser** [comment]
I'm the author of pyspelling. I haven't really used this action, but to be honest, it isn't too difficult to get it working by doing a simple action configuration: https://facelessuser.github.io/pyspelling/#usage-in-ci.

We use pyspelling in GitHub actions in the project itself, we use tox, but you don't have to: https://github.com/facelessuser/pyspelling/blob/master/.github/workflows/build.yml#L33.

**Comment by chipitsine** [comment]
that is fixed in master, but not yet released https://github.com/rojopolis/spellcheck-github-actions/commit/cad760663bf71dbdcb926a118dd4695b42019d38

@rojopolis , can you tag new release, please ?

**Comment by rojopolis** [comment]
New release is created 0.3.0 @chipitsine thanks for the heads up...  I wasn't getting notified of open issues.
