### ISSUE TITLE
Using tags for release management

### ISSUE THREAD

**Issue by andy5995** [rojopolis/spellcheck-github-actions#150]
You may want to use this approach to releases so users won't have to update their action as often:

[Using tags for release management](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management)

[Actions-R-Us/actions-tagger](https://github.com/Actions-R-Us/actions-tagger)

**Comment by jonasbn** [comment]
Hi @andy5995 

I have actually tagged a `v0` for quite some time in DockerHub. I have been somewhat reluctant to documenting it properly and recommending it since, it somehow _felt wrong_, in that sense I want the users to be made aware of the code that is changed in their repository with the releases.

From a security standpoint there, the problem is the same since a tag could just as easily be moved, so unless a release of a GitHub Action be signed, the challenge is the same.

I will evaluate the resources you provided and will I will document the option of using canonical versions like `v0` (and `v1` when we get there), so updates/releases will be less of work.

**Comment by andy5995** [comment]
> I will evaluate the resources you provided and will I will document the option of using canonical versions like `v0` (and `v1` when we get there), so updates/releases will be less of work.

Sounds good!

I'll just add this example of where this is used:

https://github.com/actions/checkout/tags

You see there have been a few 3.x releases of actions/checkout. The v3 tag points to the latest.

>I want the users to be made aware of the code that is changed in their repository with the releases.

That makes sense; though for users who are concerned about code changes between point releases, I'd say it's their responsibility to subscribe to release notifications from your repo. They have the choice of checking the changelog or reviewing the code before continuing to use the action.

**Comment by jonasbn** [comment]
Hi @andy5995 

I have updated the documentation and added a `v0` release. You are welcome to try it out. I am evaluating the various options for automating the process

**Comment by andy5995** [comment]
Thanks @jonasbn ! I'm trying it out at https://github.com/theimpossibleastronaut/rmw/pull/388 but got some errors. Any ideas?

```
Using pyspelling on configuration outlined in >spellcheck.yaml<
Checking files matching specified outlined in >spellcheck.yaml<
----------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/pyspelling", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyspelling/__main__.py", line 30, in main
    return run(
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/pyspelling/__main__.py", line 55, in run
    for results in spellcheck(
  File "/usr/local/lib/python3.11/site-packages/pyspelling/__init__.py", line 616, in spellcheck
    config = util.read_config(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyspelling/util/__init__.py", line 186, in read_config
    raise ValueError(
ValueError: Unable to find or load pyspelling configuration from spellcheck.yaml, for more details on configuration please read https://facelessuser.github.io/pyspelling/configuration/
```

**Comment by andy5995** [comment]
Disregard, I got it figured out. :)

**Comment by jonasbn** [comment]
Hi @andy5995 

Good to hear, else let me know and I will do me best to assist you.

Have a nice day
